### ISSUE TITLE
Pegar um item do carrinho especifico

### ISSUE THREAD

**Issue by sergiopeluzzi** [juliobitencourt/laravel-cart#2]
Não sei se existe essa possibilidade, se sim, peço encarecidamente que explique, caso n, acredito ser uma boa implementação.
Meu problema é que não sei como pegar um item específico que ja está no carrinho. Exemplo, tenho 4 itens e quero pegar os dados do item 2.

**Comment by juliobitencourt** [comment]
@sergiopeluzzi Como o carrinho retorna um array de itens na função all() você pode acessar qualquer item pela chave deste array. Ou ainda você pode passar o resultado para uma collection do laravel e usar seus métodos.

Caso mesmo assim você precise de uma solução específica me avise ;)
