### ISSUE TITLE
When I enter a negative quantity to update, I expect the item to be deleted

### ISSUE THREAD

**Issue by eneskaya** [juliobitencourt/laravel-cart#5]
... right now the quantity is set to negative numbers. I think this should not be expected behaviour.

**Comment by juliobitencourt** [comment]
Fixed. The negative numbers now throws an InvalidArgumentException

https://github.com/juliobitencourt/laravel-cart/commit/46c6687efa789700a3fb4335dfb5718b7f963ab7
